name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ohtehila/webapp:${{github.run_number }}-${{github.sha }}
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER }} -p ${{secrets.DOCKER_PASS }}
    - name: push the Docker image
      run: docker push ohtehila/webapp:${{github.run_number }}-${{github.sha }}
